[package]
name = "web-page-flexible-fast-easy-image-converter"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
tokio = { version = "1.27.0", features = ["full"] }
log4rs = "1.2.0"
